# Backend s? ch?y ? c?ng 8080
server.port=8080
server.address=127.0.0.1

# ===============================
# K?T N?I DATABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/horse_racing
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# C?U HÌNH JPA (T? ??ng map Java v?i SQL)
# ===============================
# 'update' giúp t? ??ng c?p nh?t b?ng n?u code Java thay ??i
spring.jpa.hibernate.ddl-auto=update
# In ra câu l?nh SQL d??i terminal ?? d? dò l?i
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect