# Backend port config
server.port=8080
server.address=127.0.0.1

# ===============================
# DATABASE POSTGRESQL CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/horse_racing
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA & HIBERNATE CONFIG
# ===============================
# Tu dong cap nhat database khi thuc the Java thay doi
spring.jpa.hibernate.ddl-auto=update

# Hien thi cau lenh SQL duoi terminal de debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB