# Backend port config
server.port=${PORT:8080}
# server.address=127.0.0.1 (Bỏ comment để Railway có thể bind IP public)

# ===============================
# DATABASE POSTGRESQL CONNECTION
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/horse_racing}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA & HIBERNATE CONFIG
# ===============================
# Tu dong cap nhat database khi thuc the Java thay doi
spring.jpa.hibernate.ddl-autxo=update

# Hien thi cau lenh SQL duoi terminal de debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
spring.output.ansi.enabled=always

# Timezone settings
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# ===============================
# HIKARICP CONNECTION POOL CONFIG (PREVENT DISCONNECTIONS)
# ===============================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=30000
# ===============================
# CLOUDINARY CONFIG
# ===============================
cloudinary.cloud-name=ddfzdsshk
cloudinary.api-key=242973157458496
cloudinary.api-secret=GTeOSTSIZJo-XdrizMkfaGmnFaU
